#!/bin/bash
sudo systemctl stop firewalld.service
export APPRTC_HOST="centos.apprtc.com"
export ROOT=$PWD
export OUTPUT=$PWD/output
pushd ..
export PROOT=$PWD
export PATH=$PATH:$PWD/bin:$PWD/supports/gae/ubuntu
popd

if [ ! -x temp ]; then
    mkdir temp
fi

if [ ! -x output ]; then
    mkdir -p output/bin
    mkdir -p output/apprtc
fi

bash
